---
sidebar: sidebar 
permalink: concept-gcnv.html 
keywords: google cloud netapp volumes, cost, price, features, google cloud netapp volumes features, gcnv, supported regions, google regions, google cloud netapp volumes regions 
summary: Google Cloud NetApp Volumes 사용하면 기업은 클라우드에 맞춰 리팩토링할 필요 없이 성능 집약적이고 지연 시간에 민감한 핵심 비즈니스 핵심 애플리케이션을 Google로 마이그레이션하고 실행할 수 있습니다. 
---
= Google Cloud NetApp Volumes 에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud NetApp Volumes는 완전 관리형 클라우드 기반 데이터 스토리지 서비스로서, 고급 데이터 관리 기능과 확장성이 뛰어난 성능을 제공합니다.

NetApp Volumes는 온프레미스 스토리지의 성능과 기능을 유지하면서 배포 시간을 단축하고, 워크로드와 애플리케이션을 관리하고, 워크로드를 클라우드로 마이그레이션하는 데 도움이 됩니다.



== 피처

* 엔터프라이즈 앱을 더 빠르고 효율적으로 실행합니다.
* 클라우드 저장 비용을 최대 90%까지 절감합니다.
* 가동 시간, 가용성 및 보안에 대한 요구 사항을 충족합니다.
* NFS, SMB 및 다중 프로토콜 환경을 지원합니다.




== 비용

Google Cloud NetApp Volumes 에서 생성된 볼륨은 BlueXP 아닌 서비스 구독에 따라 요금이 청구됩니다.

BlueXP 에서 Google Cloud NetApp Volumes 지역이나 볼륨을 검색하는 데 비용은 없습니다.



== 지원 지역

https://cloud.google.com/netapp/volumes/docs/discover/service-levels#supported_regions["지원되는 Google Cloud NetApp Volumes 지역 보기"^]



== 도움말 보기

기술 지원을 받으려면 Google Cloud 포털을 통해 요청을 등록하세요. Google Cloud 구독을 선택하고 *스토리지*에서 * Google Cloud NetApp Volumes* 서비스를 선택하세요. 필요한 정보를 입력하세요.

BlueXP 에서 Google Cloud NetApp Volumes 운영에 대한 일반적인 질문은 BlueXP 채팅을 이용하세요.

Google Cloud NetApp Volumes 에 대한 일반적인 질문은 gcinfo@netapp.com으로 NetApp의 Google Cloud 팀에 이메일을 보내주세요.

클라우드 볼륨과 관련된 기술 문제의 경우 Google Cloud Console에서 기술 지원 케이스를 생성할 수 있습니다. 자세한 내용은 을 link:https://cloud.google.com/netapp/volumes/docs/support["지원을 받는 중입니다"^] 참조하십시오.



== 관련 링크

* https://cloud.google.com/netapp/volumes/docs/discover/overview["Google Cloud NetApp Volumes 문서"^]
* https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["BlueXP 복사 및 동기화 문서"^]

